### ISSUE TITLE
Question: Classifiers used

### ISSUE THREAD

**Issue by pavinjosdev** [tasdikrahman/spammy#6]
Hi team,

~~Does Spammy use Naive Bayes or SVM classifier? I'm guessing more towards SVM as Plino describes it as Machine Learning.~~

Also is Plino an HTTP implementation/API for Spammy or are there any other changes to it?

EDIT: Plino's github page describes it as using Naive Bayes which I guess is still ML (but very outdated); it doesn't understand context and can't keep up with the evolving nature of spam.

My final question is can Spammy be rewritten to use [SVM](https://en.wikipedia.org/wiki/Support_vector_machine) or perhaps [LSA](https://en.wikipedia.org/wiki/Latent_semantic_analysis)?

Kind Regards,
Pavin Joseph.

**Comment by tasdikrahman** [comment]
Hey Pavin, 

> Also is Plino an HTTP implementation/API for Spammy or are there any other changes to it? Plino's github page describes it as using Naive Bayes which I guess is still ML (but very outdated); it doesn't understand context and can't keep up with the evolving nature of spam.

That's correct.

> My final question is can Spammy be rewritten to use SVM or perhaps LSA?

I would really like to, but I having a hard time finding time maintaining this library myself. Please feel free to fork it and use it in whatever way you feel good. 

Cheers, 
Tasdik
